### ISSUE TITLE
The installation instructions for Linux are incorrect

### ISSUE THREAD

**Issue by dtluna** [DoGyAUT/cd#43]
I run ``git clone https://github.com/DoGyAUT/OpenRA cd && cd cd && git clone https://github.com/DoGyAUT/OpenRA.Mods.AS && cd mods && git clone https://github.com/DoGyAUT/cd && cd .. && make all``
and get
```
OpenRA.Mods.AS/Traits/Render/WithVoxelAnimatedBody.cs(18,19): error CS0234: The type or namespace name `Cnc' does not exist in the namespace `OpenRA.Mods'. Are you missing an assembly reference?
OpenRA.Mods.AS/Traits/Render/WithVoxelHelicopterBody.cs(18,19): error CS0234: The type or namespace name `Cnc' does not exist in the namespace `OpenRA.Mods'. Are you missing an assembly reference?
Compilation failed: 2 error(s), 0 warnings
```

**Comment by dtluna** [comment]
I have got CD to work with [these commands](https://spit.mixtape.moe/view/d1b14d27).

**Comment by GraionDilach** [comment]
The compilation issue seems to be GraionDilach/OpenRA(.Mods.AS) issue so that'll be fixed in upstream and not here. It must be something really recent related to the everything-merged-to-the-Cnc-DLL.

**Comment by GraionDilach** [comment]
This compilation issue was introduced in https://github.com/GraionDilach/OpenRA.Mods.AS/commit/48c75929bd811b973c383929b4c6a0efad1dbb95 and can be fixed by the following diff in OpenRA:

```diff
Makefile
@@ -168,8 +168,8 @@ mod_d2k: $(mod_d2k_TARGET)
 mod_as_SRCS := $(shell find OpenRA.Mods.AS/ -iname '*.cs')
 mod_as_TARGET = mods/as/OpenRA.Mods.AS.dll
 mod_as_KIND = library
-mod_as_DEPS = $(STD_MOD_DEPS) $(mod_common_TARGET)
-mod_as_LIBS = $(COMMON_LIBS) $(STD_MOD_LIBS) $(mod_common_TARGET)
+mod_as_DEPS = $(STD_MOD_DEPS) $(mod_common_TARGET) $(mod_cnc_TARGET)
+mod_as_LIBS = $(COMMON_LIBS) $(STD_MOD_LIBS) $(mod_common_TARGET) $(mod_cnc_TARGET)
 PROGRAMS += mod_as
 mod_as: $(mod_as_TARGET)
```

Said diff is already applied to GraionDilach/OpenRA, so it's @DoGyAUT's time to update the repos here to have this issue fixed.

**Comment by dtluna** [comment]
Now everything compiles and works. Thanks, @GraionDilach .
